/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditRuleDialog.java
 *
 * Created on 16.11.2009, 14:11:05
 */

package lindenmayer.gui;

/**
 *
 * @author user
 */
public class EditRuleDialog extends javax.swing.JDialog {

    /** Creates new form EditRuleDialog */
    public EditRuleDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblInput = new javax.swing.JLabel();
    txtInput = new javax.swing.JTextField();
    lblProduction = new javax.swing.JLabel();
    txtProduction = new javax.swing.JTextField();
    btnOk = new javax.swing.JButton();
    btnCancel = new javax.swing.JButton();
    lblProductionEval = new javax.swing.JLabel();
    lblEvalMessage = new javax.swing.JLabel();

    setTitle("Regel erstellen oder bearbeiten");
    setResizable(false);

    lblInput.setText("Eingabevariable:");

    lblProduction.setText("Produktion:");

    btnOk.setText("Ok");

    btnCancel.setText("Abbrechen");

    lblProductionEval.setText("   ");

    lblEvalMessage.setText("   ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblEvalMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblInput)
              .addComponent(lblProduction))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(txtProduction, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
              .addComponent(txtInput, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
              .addComponent(lblProductionEval, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(btnCancel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnOk)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblInput)
          .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblProduction)
          .addComponent(txtProduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lblProductionEval)
        .addGap(5, 5, 5)
        .addComponent(lblEvalMessage)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnOk)
          .addComponent(btnCancel))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRuleDialog().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancel;
  private javax.swing.JButton btnOk;
  private javax.swing.JLabel lblEvalMessage;
  private javax.swing.JLabel lblInput;
  private javax.swing.JLabel lblProduction;
  private javax.swing.JLabel lblProductionEval;
  private javax.swing.JTextField txtInput;
  private javax.swing.JTextField txtProduction;
  // End of variables declaration//GEN-END:variables

}
