/*
 *  Lindenmayer
 *  see AUTHORS for a list of contributors.
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package lindenmayer.gui;

import javax.swing.JDialog;
import lindenmayer.Config;
import lindenmayer.grammar.TreePlant;
import lindenmayer.i18n.Lang;

/**
 * Panel that allows the editing of configuration values.
 * @author Christian Lins
 */
@SuppressWarnings("serial")
class ConfigPanel extends javax.swing.JPanel {

	private static final String[] LANGUAGES = new String[]
		{
			"", "<Autodetect>",
			"de", "Deutsch",
			"en", "English"
		};

	private JDialog parent;

	/** Creates new form ConfigPanel */
	public ConfigPanel(JDialog dialog) {
		initComponents();
		Utils.centerOnFrame(MainFrame.getInstance(), dialog);

		this.parent = dialog;

		// Load localized strings
		this.lblTitle.setText(Lang.get(5)); // "Edit configuration values here"
		this.lblTurtleDrawingAngle.setText(Lang.get(6)); // "Drawing angle (degree):"
		this.btnCancel.setText(Lang.get(7)); // "Cancel"
		this.lblLanguage.setText(Lang.get(32)); // "Language"

		loadFromConfig();
	}

	/**
	 * Loads the configuration values from program config to dialog.
	 */
	private void loadFromConfig() {
		// Load the turtle angle
		float tangle = Config.inst().get(
				Config.TURTLE_ANGLE, TreePlant.DEFAULT_HEADING);
		this.txtDrawingAngle.setText(Float.toString(tangle));
		String lang = Config.inst().get(Config.LANGUAGE, "");
		for(int n = 0; n < LANGUAGES.length; n += 2) {
			if(LANGUAGES[n].equals(lang)) {
				this.cmbLanguage.setSelectedItem(LANGUAGES[n + 1]);
			}
		}
	}

	/**
	 * Stores the changed configuration values of the dialog to program config.
	 */
	private void saveToConfig() {
		// Store the turtle angle (in degree not radians)
		float tangle = Float.parseFloat(this.txtDrawingAngle.getText());
		Config.inst().set(Config.TURTLE_ANGLE, tangle);
		for (int n = 0; n < LANGUAGES.length; n += 2) {
			if (LANGUAGES[n + 1].equals((String)cmbLanguage.getSelectedItem())) {
				Config.inst().set(Config.LANGUAGE, LANGUAGES[n]);
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblTurtleDrawingAngle = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtDrawingAngle = new javax.swing.JTextField();
        lblLanguage = new javax.swing.JLabel();
        cmbLanguage = new javax.swing.JComboBox();

        lblTitle.setFont(lblTitle.getFont().deriveFont(lblTitle.getFont().getStyle() | java.awt.Font.BOLD));
        lblTitle.setText("Edit configuration values");

        lblTurtleDrawingAngle.setText("Drawing angle (degree °):");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtDrawingAngle.setText("30");

        lblLanguage.setText("Language:"); // NOI18N
        lblLanguage.setName("lblLanguage"); // NOI18N

        cmbLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Autodetect>", "Deutsch", "English" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTurtleDrawingAngle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLanguage, 0, 152, Short.MAX_VALUE)
                            .addComponent(txtDrawingAngle, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurtleDrawingAngle)
                    .addComponent(txtDrawingAngle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLanguage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

  private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
	  this.parent.setVisible(false);
  }//GEN-LAST:event_btnCancelActionPerformed

  private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
	  saveToConfig();
	  this.parent.setVisible(false);
  }//GEN-LAST:event_btnOkActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbLanguage;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTurtleDrawingAngle;
    private javax.swing.JTextField txtDrawingAngle;
    // End of variables declaration//GEN-END:variables
}
