/*
 *  Lindenmayer
 *  see AUTHORS for a list of contributors.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package lindenmayer.gui;

import javax.swing.SwingUtilities;
import lindenmayer.i18n.Lang;

/**
 * Dialog that allows editing of Lindenmayer rule.
 * @author Kai Ritterbusch
 */
@SuppressWarnings("serial")
class EditRuleDialog extends javax.swing.JDialog {

	private RuleDialogCallback callback = null;

	/** Creates new form EditRuleDialog */
	public EditRuleDialog() {
		initComponents();
		Utils.centerOnFrame(MainFrame.getInstance(), this);

		btnOk.setText(Lang.get(41));
		btnCancel.setText(Lang.get(7));
		lblInput.setText(Lang.get(42));
		lblProduction.setText(Lang.get(43));
	}

	public String getInput() {
		return this.txtInput.getText();
	}

	public String getProduction() {
		return this.txtProduction.getText();
	}

	public void setCallback(RuleDialogCallback callback) {
		this.callback = callback;
	}

	public void setInput(String input) {
		this.txtInput.setText(input);
	}

	public void setProduction(String prod) {
		this.txtProduction.setText(prod);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

        lblInput = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        lblProduction = new javax.swing.JLabel();
        txtProduction = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblProductionEval = new javax.swing.JLabel();
        lblEvalMessage = new javax.swing.JLabel();

        setTitle("Regel erstellen oder bearbeiten");
        setModal(true);
        setResizable(false);

        lblInput.setText("Input variable:");

        txtInput.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKeyTyped(evt);
            }
        });

        lblProduction.setText("Production:");

        txtProduction.setFont(new java.awt.Font("Monospaced", 0, 14));
        txtProduction.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProductionKeyTyped(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.setEnabled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblProductionEval.setText("   ");

        lblEvalMessage.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEvalMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInput)
                            .addComponent(lblProduction))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProduction, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(txtInput, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                            .addComponent(lblProductionEval, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInput)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduction)
                    .addComponent(txtProduction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProductionEval)
                .addGap(5, 5, 5)
                .addComponent(lblEvalMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
		if(callback != null) {
			callback.dialogOk(this);
		}
		setVisible(false);
	}//GEN-LAST:event_btnOkActionPerformed

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
		setVisible(false);
	}//GEN-LAST:event_btnCancelActionPerformed

	private void txtInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKeyTyped
		SwingUtilities.invokeLater(new Runnable() {

			public void run() {
				checkForInput();
			}
		});
	}//GEN-LAST:event_txtInputKeyTyped

	private void txtProductionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProductionKeyTyped
		SwingUtilities.invokeLater(new Runnable() {

			public void run() {
				checkForInput();
			}
		});
	}//GEN-LAST:event_txtProductionKeyTyped

	private void checkForInput() {
		if(txtInput.getText().length() > 0 && txtProduction.getText().length() > 0) {
			this.btnOk.setEnabled(true);
		} else {
			this.btnOk.setEnabled(false);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblEvalMessage;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblProduction;
    private javax.swing.JLabel lblProductionEval;
    private javax.swing.JTextField txtInput;
    private javax.swing.JTextField txtProduction;
    // End of variables declaration//GEN-END:variables
}
